language: node_js
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build

before_deploy: npm version --git-tag-version=false "1.1.0-RC.$TRAVIS_BUILD_NUMBER"

deploy:
  - provider: script
    script: ./tools/deploy_new_release.sh
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    tag: next
    on:
      branch: develop
